name: TailCatch
version: '2.2.2'
main: com.koma.tailcatch.TailCatchPlugin
api-version: '1.20'
depend: [ProtocolLib]
commands:
  꼬리잡기:
    description: 꼬리잡기 메인 명령어
    usage: /꼬리잡기 <시작|종료|월드보더>
  닉네임:
    description: 닉네임과 색깔을 변경합니다
    usage: /닉네임 <이름> <색깔>
